directory_to_save_journals_pdf_file: "/home/daniel/Projects/Python/vak_i_tochka_parser/files/journals/"
directory_to_save_passports_pdf_files: "/home/daniel/Projects/Python/vak_i_tochka_parser/files/passports/"
directory_to_save_output_files: "/home/daniel/Projects/Python/vak_i_tochka_parser/files/output/"
directory_to_save_temporary_files: "/home/daniel/Projects/Python/vak_i_tochka_parser/files/temp/"
filename_to_save_journals_pdf: "journals.pdf"
filename_to_save_temporary_journals_json: "temp_journals.json"
filename_to_save_output_journals_json: "output_journals.json"
filename_to_save_temporary_passports_json: "temp_passports.json"
filename_to_save_output_passports_json: "output_passports.json"
